language: node_js

node_js:
  - 10

before_script:
  - npm install -g gulp-cli

script: gulp

deploy:
  - provider: s3
  - provider: codedeploy
    access_key_id: "ACCESS KEY"
    secret_access_key: "SECRET KEY"
    bucket: "S3 Bucket"
    key: latest/MyApp.zip
    application: MyApp
    deployment_group: DeploymentGroup1