language: node_js

node_js:
  - 10

before_script:
  - npm install -g gulp-cli

script: gulp

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  region: eu-west-2
  app: Portfolio
  env: node-express-env
  on:
    repo: matty9090/Portfolio
    branch: master
  bucket_name: $AWS_BUCKET
  bucket_path: "Portfolio"